# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: localhost (MySQL 5.7.17)
# Database: test-wedding
# Generation Time: 2017-03-30 02:26:16 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table email_templates
# ------------------------------------------------------------

LOCK TABLES `email_templates` WRITE;
/*!40000 ALTER TABLE `email_templates` DISABLE KEYS */;

INSERT INTO `email_templates` (`id`, `user_id`, `template_content`, `template_footer`, `template_title`, `template_type`)
VALUES
	(1,0,'\rÊ\rCongratulations and thank you for your Wedding Officiant inquiry.\rÊ\rI am available to officiate your wedding.Ê If you are interested in an \'Introductory Meeting,\' please give me a call or e-mail me to arrange a time and place.  I am available most weekdays and evenings and some Saturday mornings to meet with you. Also, let me know where will you be coming from so we can find a convenient location.\rÊ\rMy objective is to help you create a wedding ceremony reflecting your values and making the process as stress-free as possible.Ê To that end \"Your Complete Wedding Ceremony eBook\", a planning tool to help plan your ceremony, will be sent to you complements of Minnesota Officiants upon receipt of your deposit. (Click on link below for more information on eBook.)','www.MinnesotaOfficiants.com\rwww.WeddingCeremonyBooks.com','Request Initial Contact 1','Request'),
	(2,0,'\r\rCongratulations on your upcoming wedding!\rThank you for inquiry at Minnesota Officiants, although the officiants you requested are booked,ÊI am availableÊon your wedding dayÊandÊwould be delighted to perform your ceremony.\rIf you\'d like to get together for an introductory meeting please email or call me and we\'ll arrange a time and place, typically a coffee shop.\rMy objectives are to help you create a meaningful and memorable ceremony reflecting your values and preferences, while keeping the process easy and fun.\rShould we decide to work together, you would receive a complimentary copy of \"Your Complete Wedding Ceremony eBook\" to help plan your ceremony. (You may click on the link below for more information on the eBook).\rI look forward to hearing from you soon.\r\rThank you,\r\r\r','www.MinnesotaOfficiants.com\rwww.WeddingCeremonyBooks.com','Request Initial contact substitute','Request'),
	(3,0,'\r\rI enjoyed our meeting but have not heard back from you. I have received another request for the date you picked for your wedding. Unfortunately I can\'t hold the date with out a deposit. If you are still interested in having me officiate at your ceremony please let me know as soon as possible.  \r\rThank you','www.minnesotaofficiants.com','After Interview Followup','Request'),
	(4,0,'I hope that your wedding plans are coming along smoothly. If you could please get me the answers to your four questions, that would help me get them into your ceremony in a way that will flow nicely. Remember that the answers do not need to be long or term paper quality. Say what is in your heart. \rI look forward to receiving this information as it is an integral part of your wedding ceremony.\r\rThank You,','www.minnesotaofficiants.com','Ask for 4 question','Wedding'),
	(5,0,'As your wedding date draws near, it would be good to get together to review the final copy of your wedding ceremony. We can meet and I will read over the whole wedding ceremony so we can get a feel for how it sounds and if there are any additions or changes that you\'d like to make. \r\rPlease let me know when you\'re available to meet.\r\rThank you,','www.minnesoataofficiants.com','start ceremony','Wedding'),
	(6,0,'Thank you so much for letting me be a part of your wedding --- it will always be a special memory of mine.\r\rAttached is a PDF of your wedding certificate that will be filed with the county on Monday.  It is not a legal document, but is often sufficient documentation for insurance and other non-governmental changes.  \r\rThe included link provides information on name changes. \r\rYour certified copy of your wedding certificate should arrive within 2 weeks.  If you do not receive it within 3 weeks, please let me know and I will run a trace on it.\r\rAgain, many thanks!\r','http://www.minnesotaofficiants.com/name_change.htm ','thank you w/license','Wedding'),
	(7,0,'It has been over three weeks since your wedding and I want to make sure you received your Marriage Certificate.  If you have not received it, please let me know and I will run a trace on it.\r\rAlso, if you would be so kind as to write a review for me at the following links, it would be greatly appreciated.  (If your mother/father are up to writing a review, please forward this to them.)  \r\r¥	Wedding Wire: http://tinyurl.com/WeddingWireMN\r\r¥	TheKnot.com:  If you are registered with them, a review would be appreciated.  http://tinyurl.com/TheKnot-MN\r\r¥	I would love to post a picture of the two of you, your families, etc. on our website --- I do not need to be in the photo.  Also, for privacy reasons, no last names will be used. \r\rAgain thanks...\r\r','https://www.theknot.com/content/name-change-101','review and license follow up','Wedding'),
	(8,0,'\rÊ\rThank you for your Wedding Officiant inquiry and congratulations.\rÊ\rThis is a follow-up e-mail regarding your request for an officiant for your upcoming wedding. I have not received a reply to my first e-mail and wanted to inquire if you still are looking for some one to perform your ceremony. If so please respond to this e-mail or call me at my number below to make arrangements for an initial meeting to discus your ceremony.\r ','www.MinnesotaOfficiants.com\rwww.WeddingCeremonyBooks.com','Request Second Email','Request'),
	(9,0,'Thank you for allowing me to be a part of your wedding ceremony. I know we can create the perfect ceremony for your special day. Attached you will find the wedding e-book we can use to start creating the full ceremony. Please look at the wedding outline at the beginning of the book, read through the examples and note the ones that fit your values. From here we can create just the right ceremony.\r\rThank you\r','','Send Ebook','booking'),
	(10,0,'Sorry if there was a problem with the original transmission of the Wedding eBook. I am resending the book Please let me know when you have received this e-mail and the book\r\rThank you\r','','re-Send Ebook','Wedding'),
	(11,0,'Thank you so much for letting me be a part of your wedding. I have booked the date for you on my schedule so feel assured that your wedding date is reserved. I also requested the ebook \"Your Complete Wedding\" be sent to you. Please let me know if you have not received the ebook so I can renew the request.\r\r\rI look forward to your wedding day.\rThank you again,\r','www.minnesoataofficiants.com','After Booking','Wedding'),
	(12,75,'\rIt is time to create your ceremony. If you have reviewed the wedding ceremony ebook, please let me know what choices you have picked out. For any that you are unsure of. or have several in mind, we can meet in person or by phone to help find selections that work. We should also clarify any readings or rituals that you want to include and make sure you know what to bring for rituals. If there are any other questions you have about the ceremony or any other aspect of the wedding that I could help with let me know. If you want to set up a meeting, please reply to this email with your availability and we can schedule time.\r\r\r','http://minnesotaofficiants.com/ceremonies/','akl Start Ceremony','Wedding'),
	(13,75,'another email','','akl two','Test'),
	(14,0,'\rÊ\rCongratulations and thank you for your Wedding Officiant inquiry.\rÊ\rI am available to officiate your wedding.Ê If you are interested in an \'Introductory Meeting,\' please give me a call or e-mail me to arrange a time and a place.Ê I am available most weekdays and evenings and some Saturday mornings to meet with you.Ê Also, let me know where will you be coming from so we can find a convenient location.\rÊ\rMy objective is to help you create a wedding ceremony reflecting your values and making the process as stress-free as possible.Ê To that end \"Your Complete Wedding Ceremony eBook\", a planning tool to help plan your ceremony, will be sent to you complements of Minnesota Officiants upon receipt of your deposit. (Click on link below for more information on eBook.)','www.MinnesotaOfficiants.com\rwww.WeddingCeremonyBooks.com','Request Initial Contact test','Test'),
	(17,75,'\rI want you to know how much I enjoyed meeting both of you. I have not heard back from you and wanted to know if there were any other questions or concerns that you have. I know we all have busy schedules and things can slip our attention so I just wanted to touch base once again. Please let me know if you are interested in reserving my services for your wedding date. We can make arrangements for making the deposit by check, credit card or online. Please let me know at your earliest convenience. \rYou can use the link below to see fee listings.','http://minnesotaofficiants.com/fees/','AKL After first meeting','Request'),
	(18,75,'\rThings to remember for the wedding day\rBreath.\rBring the license\rBring rings\rBring the ritual articles\rBring the final payment for officiant\ramount due \r','','akl before wedding','Wedding'),
	(19,1,'\rThank you so much for allowing me to be a part of your wedding ceremony.\r\rYou should have received your Marriage Certificate from the county by now.  If you have not received it within another week, please let me know and I will initiate a trace on it.\r\rAlso, if you would post a review of my services, it would be greatly appreciated.  Places to make a post include:\r\r¥  TheKnot.com --- if you have registered with them, a review would be appreciated.\rhttp://www.theknot.com/  \r\r¥  WeddingWire.com --- no registration required.\rhttp://www.weddingwire.com/shared/Rate?vid=3f37e143ee1e5f83\r\r¥  I would love to post a picture of the two of you, your families, etc. on my website --- I do not need to be in the photo.  Also, for privacy reasons, no last names will be used. \r\r¥  And lastly, if you have a video of your ceremony, please send me the link.\r \rAgain thanks!','','JDA Reviews','Wedding'),
	(20,75,'\rThank you so much for letting me be a part of your wedding, it was a pleasure being a part of such a joyous occasion.  \r\rAttached is a PDF of your wedding certificate that will be filed with the county.  It is not a legal document, but is often sufficient documentation for insurance and other non-governmental changes.  \r\rThe included link provides information on name changes. \r\rYour certified copy of your wedding certificate should arrive within 2 weeks.  If you do not receive it within 3 weeks, please let me know and I will run a trace on it.\r\rAgain, many thanks!\r','https://www.theknot.com/content/name-change-101','akl Thankyou with license','Wedding'),
	(21,4,'','','KGInitialEmail ','Wedding'),
	(22,75,'\rhi this is a test','','akl letter','Test'),
	(23,75,'\rSince I have not had a reply to my earlier e-mails, I am assuming that you have made other arrangements or are no longer interested in my services. If you still want to discus arrangements for your wedding ceremony, please e-mail or call me at the number below, otherwise I will consider this inquiry  closed. \r\rThank you very much for your consideration of Minnesota Officiants for your wedding needs.','http://www.minnesotaofficiants.com','AKL Last Email','Request'),
	(24,72,'\r\r\'Your Love Story\' is a piece that I really love to add to my ceremonies.  It is a great way to personalize and lighten up your ceremony.  Below are 5 questions for you each to answer separately and get back to me without sharing your answers with each other.  I will combine them to create \'Your Love Story\'.  Don\'t worry, I don\'t add anything that one of you has not shared with me.  \r\rHave fun with it and just answer from your hearts!\r\r1)  How did you meet?\r\r\r\r2)  What attracted you to the other?\r\r\r\r3)  What makes your relationship work?\r\r\r\r4)  What do you love about the other?\r\r\r\r5)  What is a favorite moment you have had together?\r\r\r\r6)  Anything else you would like to share?\r\r\rI look forward to putting together Your Love Story!!\r\rKen\r612-251-3271\r715-463-2337\r','','Love Story','Wedding'),
	(27,80,'\rYour Love Story is a piece that I really love to add to my ceremonies.  It is a great way to personalize and lighten up your ceremony.  Below are 5 questions for you each to answer separately and get back to me without sharing your answers with each other.  I will combine them to create \'Your Love Story\'.  Don\'t worry, I don\'t add anything that one of you as not shared with me.\r\rHave fun with it and just answer from your hearts!\r\r1)  How did you meet?\r\r\r\r\r2)  What attracted you to the other?\r\r\r\r\r3)  What makes your relationship work?\r\r\r\r\r4)  What do you love about the other?\r\r\r\r\r5)  What is a favorite moment you have had together?\r\r\r\r\r6)  Anything else you would like to share?\r\r\r\r\rI look forward to putting together Your Love Story!!','','Love Story','Test'),
	(28,80,'','','','Test'),
	(29,67,'\r\r\rThank you for your Wedding Officiant inquiry and congratulations!\r	\rÊI am available to officiate your wedding and would be excited to talk with you about your upcoming ceremony.ÊÊ If you are interested in an \'Introductory Meeting,\' please give me a call or email me to arrange a time and a place.Ê I am available most weekdays and evenings and some Saturday mornings to meet with you. ÊAlso, where will you be coming from? We can choose a place to meet that is half way for both of us. I am in Woodbury. \rÊ	\rMy objective is to help you create a wedding ceremony reflecting your values and making the process as stress-free as possible.Ê To that end, \"Your Complete Wedding Ceremony eBook,\" is a planning tool to help plan your ceremony.Ê We have this available to you at no additional charge. It makes the planning fun!\r\rHere is my phone number but emailing me works great too. Lets plan a time to meet.\r\rThanks,\rJen Gori\r651-398-2143\r\rps I do most of the premarital counseling for the Minnesota Officiants website . Here is my website so you can check me out. This is in no way a requirement. \rwww.premaritalprep.com\r\r\r','','Officiant reply','Request'),
	(30,67,'\r\rThank you for your Wedding Officiant inquiry and congratulations!\r	\rÊI am available to officiate your wedding and would be excited to talk with you about your upcoming ceremony.ÊÊ If you are interested in an \'Introductory Meeting,\' please give me a call or email me to arrange a time and a place.Ê I am available most weekdays and evenings and some Saturday mornings to meet with you. ÊAlso, where will you be coming from? We can choose a place to meet that is half way for both of us. I am in Woodbury. \rÊ	\rMy objective is to help you create a wedding ceremony reflecting your values and making the process as stress-free as possible.Ê To that end, \"Your Complete Wedding Ceremony eBook,\" is a planning tool to help plan your ceremony.Ê We have this available to you at no additional charge. It makes the planning fun!\r\rHere is my phone number but emailing me works great too. Lets plan a time to meet.\r\rThanks,\rJen Gori\r651-398-2143\r\rps I do most of the premarital counseling for the Minnesota Officiants website . Here is my website so you can check me out. This is in no way a requirement. \rwww.premaritalprep.com\r\r\r','Jen Gori 651-398-2143','officiant reply','Request'),
	(31,67,'Hello! \rJust to drop you a note to let you know what an absolute honor it was to officiate your wedding ceremony. I have mailed your marriage license and you should be getting a copy in about two to three weeks. \rIf you are a subscriber to THE KNOT would you be willing to give me a quick review. As you know, most couples are looking for officiants and only want to hear from other couples and their experiences. I would be so thankful if you wouldn\'t mind spending five minutes writing a review. This keeps me working as an officiant which is my passion!!!! Thanks so much and many blessings for an amazing future together.\rRemember, I do premarital counseling and first year counseling if you should ever hit any bumps in the road. Here is my professional website.\r\rwww.premaritalprep.com\r\rWarmly,\rJen Gori\r651-398-2143\r','','follow up','Wedding'),
	(32,72,'BRIDES NAME:\rAddress:\r\rTelephone #:\rOK to text?     \remail address:\r*********************************\rGROOMS NAME:\rAddress:\r\rOK to text?      \rTelephone #:\remail address:\r\rWedding Package: (check one)\r      _____ Budget ($175/$150) 8 or fewer guests\r\r      _____ Basic ($295) less the 50 guests\r      _____ Basic with rehearsal $395\r\r      _____ Standard ($395) more than 50 guests\r      _____ Standard with rehearsal $495\r\rNumber of Guests:\r\rCeremony Date:\r\rCeremony Time:\r\rAddress of Ceremony Location:\r\rRehearsal:    ________ Yes         ___________ No\r\rRehearsal Date:\r\rRehearsal Time:\r\rRehearsal Location:\r','Ken Pearson','Wedding Information','Test'),
	(33,72,'','','','Test'),
	(34,72,'','','','Test'),
	(35,6,'\r\r\rI enjoyed meeting with you two and hearing about your wedding plans. I wanted to follow up to see if you\'ve made a decision whether you want me to officiate at your ceremony. If you have any questions, I\'d be happy to talk with you further. \rPlease let me know either way.  \r\rThank you,\r\r','www.mnofficiants/fees.com','Nancy\'s after interview','Request'),
	(36,6,'\r\rThank you for asking about pre-marital counseling. I use the Prepare-Enrich assessment. You and your fiancŽ would take an on-line assessment which takes 30-45 minutes. After getting the results from that, it\'ll give us a good indication as to what your common approaches and differences are.\rThere are several goals of the PREPARE/ENRICH Program. In order to achieve these goals there are exercises designed to help couples improve their relationship skills. The program helps couples:\rExplore strength and growth areas\rStrengthen communication skills\rIdentify and manage major stressors\rResolve conflict using the Ten Step Model\rDevelop a more balanced relationship\rExplore family of origin issues\rDiscuss financial planning and budgeting\rEstablish personal, couple and family goals\rUnderstand and appreciate personality differences\r Our sessions would be ninety minutes each at 135.00. We\'d need at least three sessions, perhaps four. This is a good investment in your marriage. \r\rIf you and your fiancŽ are interested in moving forward, I\'d love to meet with you.\r\rThank you,\r','','Prepare Enrich ','Request'),
	(37,75,'\rThank you for asking about pre-marital counseling. I use the Prepare-Enrich assessment. You and your fiancŽ would take an on-line assessment which takes 30-45 minutes. After getting the results from that, it\'ll give us a good indication as to what your common approaches and differences are.\rThere are several goals of the PREPARE/ENRICH Program. In order to achieve these goals there are exercises designed to help couples improve their relationship skills. The program helps couples:\rExplore strength and growth areas\rStrengthen communication skills\rIdentify and manage major stressors\rResolve conflict using the Ten Step Model\rDevelop a more balanced relationship\rExplore family of origin issues\rDiscuss financial planning and budgeting\rEstablish personal, couple and family goals\rUnderstand and appreciate personality differences\rOur sessions would be ninety minutes each at $140.00. We\'d need at least three sessions, perhaps four. This is a wonderful investment in your marriage. \r\rIf you and your fiancŽ are interested in moving forward, I\'d love to meet with you.\r\rThank you,','https://www.prepare-enrich.com/','akl prepare enrich  ','Request'),
	(39,4,'Dear xxx and xxx,\r\rIt was so great meeting you on Saturday. ÊThanks a million for choosing me as your officiant. ÊI am very happy to beÊa part of your special day!Ê\r\rAttached is the I DO e-book with some ceremony samples at the back (beginning on page 126) and the template I created for you to use for yourÊceremony.ÊNo need to print the big book. ItsÊsize can beÊoverwhelming, so do not hesitate to contact me by phone orÊemail me if you have any questions at any time re the book or anythingÊelse.Ê\r\rThe best way to start is to use the __________ template doc attached and make changes, deletions, additions as you like. ÊHere are some tips for making the template work for you....theÊwhole idea is to end up with exactly what the two of you want for your awesomeÊday!Ê\r\r[if !supportLists]¥ÊÊÊÊÊÊÊÊÊÊÊÊÊÊÊ [endif]You can work on it sections at a time or all at once.Ê\r[if !supportLists]¥ÊÊÊÊÊÊÊÊÊÊÊÊÊÊÊ [endif]You can use what is in the template or copy and paste otherÊthings you like better from the big book or from any other source.\r[if !supportLists]¥ÊÊÊÊÊÊÊÊÊÊÊÊÊÊÊ [endif]There can be more than one rough draft \"entry\" in anyÊpart of the ceremony if you can\'t decide right now.\r[if !supportLists]¥ÊÊÊÊÊÊÊÊÊÊÊÊÊÊÊ [endif]You can mix and match things within vows or other sections, say different vows to each other, or create your own.Ê\r[if !supportLists]¥ÊÊÊÊÊÊÊÊÊÊÊÊÊÊÊ [endif]I will add your names when I do the finalÊdraft...no need to change all those Bride and Groom references now.Ê\rLet me know when you have a rough draft of the ceremonyÊready in the template. ÊThen the three of us can meet again to work onÊfinalizing it. Ê\rFor your records, I received the $___ deposit by Check #6949 on April 25, 2015. ÊThe balance of $___ will be due on or before the wedding. ÊÊ\rIn the meantime, just let me know if you need anythingÊat all.Ê\rThanks again and have fun creating the ceremony!Ê\rÊKate\r(612) 374-0145 Home\r(612) 598-2313 Cell\rkate@minnesotaofficiants.com\r\r\r','','KGBookedEmail ','Test'),
	(40,3,'\rCongratulations on your upcoming wedding! ÊI am available on that day, and would be honored to officiate.Ê I am happy to give you as much or as littleÊguidance and suggestions for your ceremony as you\'d like.ÊÊI aim to make the process as smooth and stress free as possible, one of the things we provide is an eBook titled \"Your Complete Wedding Ceremony eBook,\" it\'s a planning tool to helpÊbegin the process of creatingÊyour ceremony, it\'s filled with over 60 examples of vows, many reading, prayers, and so on.\rÊWhat questions do you have for me to decide if I\'m the right person for you? I\'m guessing you read my little bio on the web site, but if you didn\'t there is a link below if you want to check it out.\rI look forward to talking with you further\r\r\r\r\r\r','Winner: Wedding WireÕs BrideÕs Choice Awardsª 2015','Je Intro','Request'),
	(42,75,'Congratulations. My name is Allan Lindgren and I am available to perform your wedding ceremony. The fees for a budget wedding (10 or fewer persons) is $175 Friday through Sunday and $150 Monday through Thursday. A deposit of 50% is required to reserve your date. I will send you a standard wedding ceremony document with several choices for vows and ring vows.  You are responsible to secure a wedding license prior to the ceremony date. If you are interested in proceeding further you can reply to this email or call me at the number in the signature.\rI look forward to hearing from you','http://minnesotaofficiants.com/officiants/allan-lindgren/','akl budget available','Request'),
	(43,4,'Dear Bride and Groom,\r\rThanks a million for choosing me as your officiant!Ê\r\rAttached is the template Word doc xandy##month17Êand the ebook for reference as you build yourÊceremony. Please save the template as AandR09sep17_v1 in case you want to come back to the original version.Ê I recommend that you keepÊthe ebook open as you work in the v1 Word doc to make changes, deletions, additions as you like. ÊI also included a sample of aÊrecent wedding for you to see what a final draft looks like and to use parts of it if you wish.Ê\r\rBelow are some tips for helping you end up with exactly what the two of you want for your awesomeÊday! ÊMy hope is that this process will be easy, fun, and stress-free. Ê\r¥ ÊYou can use what is in the template or copy and paste otherÊthings you like better from the big book, sample or from any other source.\r¥ ÊIf you canÕt decide, there can be more than one rough draft \"entry\" in anyÊpart of the ceremony. ÊWe will go over them for you to decide when we meet again. Ê\r¥ÊÊYou can mix and match things within vows or other sections, say different vows to each other, or create your own.Ê\r\rFor your records, I received payment for the weddingÊdeposit of $245 by PayPal on month day, 2017. The remainder of $250 will be due on or before the rehearsal.\r\rPlease feel free to contact me by phone orÊemail me at any time if you have questions at all. ÊI look forward to meeting you again when the rough draft is ready. Ê\r\r\rAll the Best,Ê\rKateÊ\r(612) 374-0145\rCell: (612)598-2313Ê\r\r','','KGtemplateebook','Test'),
	(45,4,'I hope you had a wonderful Holiday Season and start of 2017 as newlyweds. Thank you so much for including me in your special day. ÊI loved meeting you and hearing your love story. ÊI enjoyed the ceremony very much and hope you are pleased with how it all turned out.Ê\r\rI have a big favor to ask of you. If you would be so kind as to write a review for me viaÊWedding WireÊ(no registration required) and/orÊThe KnotÊ(if you are registered with them), it will help other couples find me on the web. \r\rAlso,ÊI would love to have a wedding photo of the two of you, and a copy of any review, for myself and also to post in my Minnesota Officiants bio if you agree.ÊI do not need to be in the photo. For privacy reasons, no last names will be used.\r\rI truly hope that this can be an easy, stress-free request for you. I really appreciate your time and feedback. Ê\r\rThanks again. I wish you all the best for many, many years together. May your love grow and deepen beyond your greatest expectations!\r\rSincerely,Ê\r\rKateÊ\r612-598-2313\r\rP.S. ÊI do great Baby Welcome ceremonies if expanding your family is in your future dreams! ÊÊ\r\r','','KGPostWeddingRqReview','Wedding');

/*!40000 ALTER TABLE `email_templates` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
