# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5577dec89eaf36c6c8e870eb4a794869d523f8d7c840cbfe7c8fe43b350bf0929413d4d53727535704f76c69d05d9dda02d8f940a435159265d187c982520541

test:
  secret_key_base: 35ecc1e24b4a557b1672e0d50fd2a886fd3d28c60a357cb1e3c92b21cfa300a5ad04dc776f6de96a7764766e1b17b87758aa9f3ea280730028080e29b6b63f1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
